# Generated by Django 3.1.2 on 2020-11-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Data_Type',
            fields=[
                ('OriginalTypeID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('OriginalSchema', models.TextField()),
                ('Mapping', models.TextField()),
                ('TaskThresHold', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SubmissionPeriod', models.IntegerField(default=0)),
                ('TableName', models.CharField(max_length=40, unique=True)),
                ('TaskSchema', models.TextField(default='')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('MainID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Parsing_Data',
            fields=[
                ('SubmissionID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SubmissionNumber', models.IntegerField()),
                ('SubmissionDate', models.DateTimeField()),
                ('StartDate', models.DateField()),
                ('FileName', models.CharField(default='', max_length=100)),
                ('EndDate', models.DateField()),
                ('NumberOfTuple', models.IntegerField()),
                ('QUanAssessment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('QUalAssessment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('P_NP', models.CharField(default='W', max_length=2)),
                ('AssessorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessor', to='raterUI.user')),
                ('OriginalTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterUI.original_data_type')),
                ('SubmitterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter', to='raterUI.user')),
            ],
        ),
        migrations.AddField(
            model_name='original_data_type',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterUI.task'),
        ),
        migrations.CreateModel(
            name='Participate_Task',
            fields=[
                ('OriginaTypeID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='raterUI.original_data_type', unique=True)),
                ('Pass', models.CharField(default='W', max_length=1)),
                ('SubmitterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterUI.user')),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raterUI.task')),
            ],
        ),
    ]
