# Generated by Django 3.1.2 on 2020-11-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('MainID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
