# Generated by Django 3.1.2 on 2020-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.CharField(max_length=20)),
                ('TableName', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
    ]
