# Generated by Django 3.1.2 on 2020-11-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Data_Type',
            fields=[
                ('OriginalTypeID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('OriginalSchema', models.TextField()),
                ('Mapping', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('MainID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('DateOfBirth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='SubmissionPeriod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='TaskSchema',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='TableName',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Parsing_Data',
            fields=[
                ('SubmissionID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SubmissionNumber', models.IntegerField()),
                ('SubmissionDate', models.DateTimeField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('NumberOfTuple', models.IntegerField()),
                ('QUanAssessment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('QUalAssessment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('P_NP', models.CharField(default='NP', max_length=2)),
                ('AssessorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessor', to='adminUI.user')),
                ('OriginalTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.original_data_type')),
                ('SubmitterID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter', to='adminUI.user')),
            ],
        ),
        migrations.AddField(
            model_name='original_data_type',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.task'),
        ),
    ]
