# Generated by Django 3.1.2 on 2020-11-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0008_auto_20201123_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='original_data_type',
            old_name='OriginalSchema',
            new_name='OriginSchema',
        ),
    ]
