# Generated by Django 3.1.2 on 2020-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0009_auto_20201124_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskID',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='MainID',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
