# Generated by Django 3.1.2 on 2020-11-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0003_auto_20201123_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate_task',
            name='id',
        ),
        migrations.AddField(
            model_name='participate_task',
            name='OriginaTypeID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminUI.original_data_type'),
        ),
    ]
