# Generated by Django 3.1.2 on 2020-11-23 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0006_auto_20201123_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate_task',
            name='OriginaTypeID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminUI.original_data_type'),
        ),
        migrations.AlterField(
            model_name='participate_task',
            name='SubmitterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.user'),
        ),
        migrations.AlterField(
            model_name='participate_task',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.task'),
        ),
    ]
